// File generation / export service.
//
// Plain text and markdown are generated entirely client-side (instant, no
// server round trip). Binary formats that need a real writer library
// (.docx / .pdf / .xlsx) are generated by POST /api/files/generate on the
// server (see server/routes/files.ts) and streamed back as a blob.

export type ExportFormat = 'md' | 'txt' | 'docx' | 'pdf' | 'xlsx';

function triggerBlobDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Give the browser a tick to start the download before revoking.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function ensureExtension(filename: string, ext: string): string {
  return filename.toLowerCase().endsWith(`.${ext}`) ? filename : `${filename}.${ext}`;
}

export const fileGenService = {
  async exportAs(format: ExportFormat, content: string, filenameBase = 'jarvis-output'): Promise<void> {
    if (format === 'md' || format === 'txt') {
      const filename = ensureExtension(filenameBase, format);
      const mime = format === 'md' ? 'text/markdown;charset=utf-8' : 'text/plain;charset=utf-8';
      triggerBlobDownload(new Blob([content], { type: mime }), filename);
      return;
    }

    const filename = ensureExtension(filenameBase, format);
    const res = await fetch('/api/files/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ format, filename, content })
    });

    if (!res.ok) {
      let message = `Failed to generate ${format.toUpperCase()} file (HTTP ${res.status}).`;
      try {
        const data = await res.json();
        if (data?.error) message = data.error;
      } catch {
        /* response wasn't JSON -- keep the generic message */
      }
      throw new Error(message);
    }

    const blob = await res.blob();
    triggerBlobDownload(blob, filename);
  },

  // Best-effort filename base from a message's content: first heading, or
  // first non-empty line, slugified and capped.
  suggestFilename(content: string): string {
    const firstLine = content.split(/\r?\n/).find((l) => l.trim())?.replace(/^#+\s*/, '') || 'jarvis-output';
    return firstLine
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 50) || 'jarvis-output';
  }
};
